server:
  port: 8181
  context-path: /auth_server

spring:
  ldap:
    embedded:
      ldif: classpath:LDAP_server.ldif
      base-dn: dc=springframework,dc=org
      port: 8182

authsrv:
  security:
    algorithm: SHA256withECDSA
    keystore:
      name: authKeyStore.jks
      password: keystorepassword
      key:
        alias: ecc256
        password: keypassword

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.ckr.msdemo.authserver: DEBUG